package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserpasswordDO;

public interface UserpasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Feb 26 17:01:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Feb 26 17:01:31 CST 2020
     */
    int insert(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Feb 26 17:01:31 CST 2020
     */
    int insertSelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Feb 26 17:01:31 CST 2020
     */
    UserpasswordDO selectByPrimaryKey(Integer id);

    UserpasswordDO selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Feb 26 17:01:31 CST 2020
     */
    int updateByPrimaryKeySelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Feb 26 17:01:31 CST 2020
     */
    int updateByPrimaryKey(UserpasswordDO record);
}